---
include:
  - board: seeeduino_xiao_ble
    shield: MKB_R rgbled_adapter
    snippet: central trackball_paw3222
    cmake-args: -DKEYMAP_FILE=$GITHUB_WORKSPACE/config/MKB.keymap
    artifact-name: MKB_R_PAW3222_Central

  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter
    snippet: peripheral trackball_pat9125
    cmake-args: -DKEYMAP_FILE=$GITHUB_WORKSPACE/config/MKB.keymap
    artifact-name: MKB_L_PAT9125_Peripheral

  # - board: seeeduino_xiao_ble
  #   shield: MKB_R rgbled_adapter
  #   snippet: central trackball_pmw3610_alt
  #   cmake-args: -DKEYMAP_FILE=$GITHUB_WORKSPACE/config/MKB.keymap
  #   artifact-name: MKB_R_PMW3610_Central

  # - board: seeeduino_xiao_ble
  #   shield: MKB_L rgbled_adapter
  #   snippet: peripheral encoder_ec11
  #   cmake-args: -DKEYMAP_FILE=$GITHUB_WORKSPACE/config/MKB.keymap
  #   artifact-name: MKB_L_ENC_Peripheral

  # ----------------------------------------------------------------------------

  # - board: seeeduino_xiao_ble
  #   shield: MKB_L_Base MKB_L_JOY rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart
  #   artifact-name: MKB_L_MODULE_JOY

  # - board: seeeduino_xiao_ble
  #   shield: MKB_L_Base MKB_L_ENC rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart
  #   artifact-name: MKB_L_MODULE_ENC

  # - board: seeeduino_xiao_ble
  #   shield: MKB_L_Base MKB_L_RZT rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart
  #   artifact-name: MKB_L_MODULE_RZT

  # - board: seeeduino_xiao_ble
  #   shield: MKB_L_Base MKB_L_TPD rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart
  #   artifact-name: MKB_L_MODULE_TPD

  # - board: seeeduino_xiao_ble
  #   shield: MKB_L_Base MKB_L_KEY rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart
  #   artifact-name: MKB_L_MODULE_KEY

  # - board: seeeduino_xiao_ble
  #   shield: MKB_R_Base MKB_R_TBv3 rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart
  #   artifact-name: MKB_R_MODULE_TBv3

  # - board: seeeduino_xiao_ble
  #   shield: MKB_R_Base MKB_R_JOY rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart
  #   artifact-name: MKB_R_MODULE_JOY

  # - board: seeeduino_xiao_ble
  #   shield: MKB_R_Base MKB_R_ENC rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart
  #   artifact-name: MKB_R_MODULE_ENC

  # - board: seeeduino_xiao_ble
  #   shield: MKB_R_Base MKB_R_RZT rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart
  #   artifact-name: MKB_R_MODULE_RZT

  # - board: seeeduino_xiao_ble
  #   shield: MKB_R_Base MKB_R_KEY rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart
  #   artifact-name: MKB_R_MODULE_KEY

  - board: seeeduino_xiao_ble
    shield: settings_reset
