# CONFIG_GPIO_HOGS=y

# Basic hardware configurations
CONFIG_I2C=y
CONFIG_PINCTRL=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Input processor configuration
# CONFIG_ZMK_INPUT_PROCESSOR_KEYBIND=y


# --- デバッグ用ログ＆シェル設定 ---
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG=y
# CONFIG_LOG_DEFAULT_LEVEL=3
# CONFIG_SHELL=y
# CONFIG_I2C_SHELL=y