# Basic hardware configurations
CONFIG_SPI=y
CONFIG_PINCTRL=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# CONFIG_INPUT_PMW3610=y

# PMW3610 optical sensor settings
CONFIG_PMW3610_ALT=y
# CONFIG_PMW3610_ALT_SWAP_XY=y
# CONFIG_PMW3610_ALT_INVERT_X=n
# CONFIG_PMW3610_ALT_INVERT_Y=n
CONFIG_PMW3610_ALT_SMART_ALGORITHM=y
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=15

CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=1000
CONFIG_PMW3610_ALT_RUN_DOWNSHIFT_TIME_MS=3264
CONFIG_PMW3610_ALT_REST1_SAMPLE_TIME_MS=20
CONFIG_PMW3610_ALT_REST3_SAMPLE_TIME_MS=300

# Input processor configuration
# CONFIG_ZMK_INPUT_PROCESSOR_KEYBIND=y

# --- デバッグ用ログ＆シェル設定 ---
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG=y
# CONFIG_LOG_DEFAULT_LEVEL=3
# CONFIG_SHELL=y
# CONFIG_I2C_SHELL=y